name: merge

on:
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: merge
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ secrets.PAT }}
          source_ref: 'jd-scripts'
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
