name: Gitee repos mirror periodic job
on:
# 如果需要PR触发把push前的#去掉
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: GuoJuna/sync-repo-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:dongdongGit/jd-scripts.git
          source_branch: main
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:gaara724/jd-tool.git
          dest_branch: main
          ssh_private_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}